### PR TITLE
protect session_start safe/mandatory options

### PR DESCRIPTION
**Pull request by pine3ree**
...just as an extra precaution, the method being private anyway

### CODE REVIEW

**Comment by pine3ree** [comment]
there is an error in the travis PHP:nightly build: composer is trying to install packages for php-8.0.0-dev :-) for which there are unresolvable dependencies.

**Comment by michalbundyra** [comment]
@pine3ree we should drop nightly build and add PHP 7.3 instead

**Review by michalbundyra — CHANGES_REQUESTED** [review]
@pine3ree We need test to cover these changes.

**Comment by pine3ree** [comment]
> @pine3ree We need test to cover these changes.

Hello @webimpress , we may add a test to verify that those values cannot be overwritten, but so far the private method `startSession` is called (internally, obviously) twice without any of the required/safe keys, thus no breaking change is added by this PR.

kind regards

PS
Another simple idea I have is to add 2 properties to `PhpPersistance`: `$requiredOptions` and default `$options`, with `$options` overwritable via config key for php-ext options pulled from the container (this would also imply a factory for PhpPersistance). A sessionStart() call would have options set in the following way:
```$this->requiredOptions + $runtimeOptions + $this->options``` $runtimeOptions being  locally defined

In this way we could safely set php-ext options in the application configuration, w/o explicitly calling ini_set(..., ...) on app bootstrap.

**Review by Ocramius — CHANGES_REQUESTED** [review]
If something is being solved here, that something **MUST** have a unit or integration test: no merge otherwise

**Comment by pine3ree** [comment]
Hello @xtreamwayz , @Ocramius.
Added test case:
1) still cannot run tests for php-nightly 8.0-dev
2) There is an unrelated [travis error](https://travis-ci.org/zendframework/zend-expressive-session-ext/jobs/490192774#L630), which pointed out what I believe to be a little bug in the test case: `testAllowsSessionToOverrideDefaultLifetime` in line [531](https://github.com/zendframework/zend-expressive-session-ext/blob/master/test/PhpSessionPersistenceTest.php#L531) (and similar in other related tests)
```php 
$this->assertSame(time() + $lifetime, $setCookie->getExpires());
```
It is assumed here that `time() + $lifetime` is equal to the value set before in the response, but that could have happen in the second before this call (just couple of microseconds are necessary 1549767356.999999 and 1549767357.000001 are different second) so the expiry times can differ by 1 second as reported in the error....

...sorry if some "q"s are missing...my keyboard's "q" is behaving oddly...

(https://github.com/zendframework/zend-expressive-session-ext/pull/38)

**Comment by weierophinney** [comment]
Thanks, @pine3ree!

**Pull request merged**
